### ISSUE TITLE
Add your corpus to the corpus directory

### ISSUE THREAD

**Issue by ftyers** [DianaComp/2017-osnov-programm#2]
You can find a reasonably-sized Tatar corpus here: 

http://ilazki.thinkgeek.co.uk/~spectre/wikipedia/tatar/wiki.txt.10k

The filename should be `wiki.txt` and it should be put in the `corpus/` subdirectory of your repository.

**Comment by DianaTisQA** [comment]
Thanks a lot!
Managed to add to the corpus/ subdirectory.

**Comment by ftyers** [comment]
Cool, you can close the issue! :)
